FROM python:3.13-slim

# Evita generar archivos .pyc
ENV PYTHONDONTWRITEBYTECODE=1

# Los logs aparecen inmediatamente
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]